// Mocks generated by Mockito 5.4.2 from annotations
// in insect_dection_app/test/helpers/auth_domain.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:insect_dection_app/core/core.dart' as _i5;
import 'package:insect_dection_app/features/auth/auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.LoginSuccessEntity>> logIn(
          _i3.LoginParams? loginParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [loginParams],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i3.LoginSuccessEntity>>.value(
                _FakeEither_0<_i5.Failure, _i3.LoginSuccessEntity>(
          this,
          Invocation.method(
            #logIn,
            [loginParams],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.LoginSuccessEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.SignUpSuccessEntity>> signUp(
          _i3.SignUpParams? signUpParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signUpParams],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i3.SignUpSuccessEntity>>.value(
                _FakeEither_0<_i5.Failure, _i3.SignUpSuccessEntity>(
          this,
          Invocation.method(
            #signUp,
            [signUpParams],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.SignUpSuccessEntity>>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i3.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.SignUpResponse>? signUp(_i3.SignUpParams? signUpParams) =>
      (super.noSuchMethod(Invocation.method(
        #signUp,
        [signUpParams],
      )) as _i4.Future<_i3.SignUpResponse>?);
  @override
  _i4.Future<_i3.LoginResponse?> logIn(_i3.LoginParams? loginParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIn,
          [loginParams],
        ),
        returnValue: _i4.Future<_i3.LoginResponse?>.value(),
      ) as _i4.Future<_i3.LoginResponse?>);
}
