name: insect_dection_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  provider: ^6.0.5
  # Firebase Services
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  # Provides the ability to load, save, and manipulate images in a variety of image file formats.
  image: ^4.0.17
  image_picker: ^1.0.2
  path: ^1.8.3
  # Provides a flexible and fast solution for 
  # accessing TensorFlow Lite interpreter and performing inference
  # TODO: current disable for dev
  tflite_flutter: ^0.10.1
  # Dont know
  video_player: ^2.7.0
  # Extra state manange for camera services
  get: ^4.6.5
  # Use camera to detection insect
  camera: ^0.10.5+3
  # Implement comparation
  equatable: ^2.0.5
  # Functional Programming
  dartz: ^0.10.1
  # State management Bloc
  flutter_bloc: ^8.1.3
  # Dependency Ineject
  get_it: ^7.6.0
  # HTTP
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  fake_cloud_firestore: ^2.4.1+1
  mock_exceptions: ^0.8.2
  firebase_storage_mocks: ^0.6.1
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/